import Head from "next/head";
import { useQuery } from "react-query";

import {
  getCollectionSort,
  getAllCollectionData,
} from "@/api/public/publicAPI";

export default function Home() {
  const collectionSort = useQuery(["collectionSort"], getCollectionSort);
  const collections = useQuery(["collections"], getAllCollectionData);

  return (
    <>
      <Head>
        <title>Wangari Mathenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Wangari Mathenge</h1>
      </main>
    </>
  );
}
